// <auto-generated />
namespace _4sqChat.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FoursquareUserContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoursquareUserContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201211262203250_FoursquareUserContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
